# Generated by Django 4.0.6 on 2022-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='value',
            field=models.IntegerField(),
        ),
    ]
