# Generated by Django 4.0.6 on 2022-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_keyval_key_alter_keyval_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
