# Generated by Django 4.0.2 on 2022-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_category_kitchen_remove_dish_ingredients_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание блюда'),
        ),
    ]
