# Generated by Django 4.0.2 on 2022-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_dish_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images', verbose_name='Картинка'),
        ),
    ]
